# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39b4ee2ef0ed6c2273df208b36a059fd"
application_url = "https://buylater.cannyapps.com"
embedded = true
name = "Buy Now Later"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_products,read_themes,write_draft_orders,write_products,read_own_subscription_contracts,write_own_subscription_contracts,read_customer_payment_methods"

[auth]
redirect_urls = [
  "https://buylater.cannyapps.com/authenticate"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "subscription_contracts/create" ]
uri = "/webhook/subscription-contract-create"

[[webhooks.subscriptions]]
topics = [ "subscription_billing_attempts/success" ]
uri = "/webhook/subscription-billing-success"

[webhooks.privacy_compliance]
customer_deletion_url = "https://buylater.cannyapps.com/webhook/customers-redact"
customer_data_request_url = "https://buylater.cannyapps.com/webhook/customers-data-request"
shop_deletion_url = "https://buylater.cannyapps.com/webhook/shop-redact"

[app_proxy]
url = "https://buylater.cannyapps.com"
subpath = "buylater-proxy"
prefix = "apps"

[build]


