# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39b4ee2ef0ed6c2273df208b36a059fd"
application_url = "https://buylater.cannyapps.com"
embedded = true
name = "Buy Now Later"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_products,read_themes,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://buylater.cannyapps.com/authenticate"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhook/customers-data-request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhook/customers-redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhook/shop-redact"

[app_proxy]
url = "https://buylater.cannyapps.com"
subpath = "buylater-proxy"
prefix = "apps"


