# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39b4ee2ef0ed6c2273df208b36a059fd"
application_url = "https://limitation-mines-cologne-praise.trycloudflare.com"
embedded = true
name = "Buy Now Later"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_all_orders,read_customers,read_themes,read_own_subscription_contracts,write_own_subscription_contracts,read_customer_payment_methods,read_draft_orders,write_draft_orders,write_purchase_options,read_purchase_options"

[auth]
redirect_urls = [
  "https://limitation-mines-cologne-praise.trycloudflare.com/authenticate"
]

[webhooks]
api_version = "2026-10"

[webhooks.privacy_compliance]
customer_deletion_url = "https://limitation-mines-cologne-praise.trycloudflare.com/webhook/customers-redact"
customer_data_request_url = "https://limitation-mines-cologne-praise.trycloudflare.com/webhook/customers-data-request"
shop_deletion_url = "https://limitation-mines-cologne-praise.trycloudflare.com/webhook/shop-redact"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
