# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39b4ee2ef0ed6c2273df208b36a059fd"
application_url = "https://buylater.cannyapps.com"
embedded = true
name = "Buy Now Later"

[navigation]
links = [
  { label = "Overview", destination = "/" },
  { label = "Orders", destination = "/bookings" },
  { label = "General Settings", destination = "/app-settings" },
  { label = "Support & Helpdesk", destination = "/support" }
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_all_orders,read_customers,read_themes,read_customer_payment_methods,read_draft_orders,write_draft_orders,read_purchase_options,write_purchase_options,read_payment_mandate,write_payment_mandate"

[auth]
redirect_urls = [
  "https://buylater.cannyapps.com/authenticate"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhook/app-uninstalled"

[[webhooks.subscriptions]]
topics = [ "orders/paid", "orders/create", "orders/updated" ]
uri = "/webhook/orders-paid"

[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "/webhook/products-update"


[webhooks.privacy_compliance]
customer_deletion_url = "https://buylater.cannyapps.com/webhook/customers-redact"
customer_data_request_url = "https://buylater.cannyapps.com/webhook/customers-data-request"
shop_deletion_url = "https://buylater.cannyapps.com/webhook/shop-redact"

[app_proxy]
url = "https://buylater.cannyapps.com"
subpath = "buylater-proxy"
prefix = "apps"

[build]
automatically_update_urls_on_dev = false
